# Usa una imagen base de oven/bun:alpine
FROM oven/bun:alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y el archivo bun.lockb
COPY package.json .

# Instala las dependencias
RUN bun install

# Copia el resto de la aplicación
COPY . .

# Compila la aplicación
RUN bun run build

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["bun", "run", "dist/main.js"]
