services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: shop-api/.
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"

  ui:
    build:
      context: shop-ui/.
      dockerfile: dockerfile
    depends_on:
      - api
    ports:
      - "4321:4321"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - ui

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mf.erick02@gmail.com -d kufumi.com -d api.kufumi.com --agree-tos

volumes:
  db_data:
