# Usa una imagen base de oven/bun:alpine
FROM node:23-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y el archivo bun.lockb
COPY package.json .

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Compila la aplicación
RUN npm run build

# Establece las variables de entorno 
ENV HOST=0.0.0.0
ENV PORT=4321

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 4321

# Comando para ejecutar la aplicación
CMD ["node", "./dist/server/entry.mjs"]
